### PR TITLE
purepower: Add a space after the prompt char.

### PR DESCRIPTION
**Pull request by infokiller**
This makes it more similar to the real pure.

### CODE REVIEW

**Comment by romkatv** [comment]
Here's how it is for me.

Pure:

pure

Pure Power without the change:

pure-power-unchanged

Pure Power with the change:

pure-power-changed

After the change there are two spaced between `❯` and the command line. Before the change there is one, just like in Pure.

Is it different from what you are seeing?

**Comment by infokiller** [comment]
Yes it's different for me, here's what I'm seeing.

Pure:
image

Pure power without the added space:
image

Pure power with the added space:
image

I'll play a bit with my zshrc to check if it's just an issue with my config and try to reproduce the issue with a minimal zshrc.

**Comment by romkatv** [comment]
There is something bad going on. Let's try to debug this.

Are you sure you have the latest version of Powerlevel10k? What's the output of `git rev-parse HEAD` in `powerlevel10k` directory?

Type `ls<tab>`. Does your prompt break?

Type `ZLE_RPROMPT_INDENT=1`. Does it help?

What's the output of `echo $ZSH_VERSION $ZSH_PATCHLEVEL`?

**Comment by romkatv** [comment]
Also, I see that your prompt doesn't look like the stock Pure Power. Can you reproduce the problem with the current unmodified version of Pure Power?

**Comment by infokiller** [comment]
Thanks for the quick response and sorry for disappearing, was AFK.

> There is something bad going on. Let's try to debug this.
> 
> Are you sure you have the latest version of Powerlevel10k? What's the output of `git rev-parse HEAD` in `powerlevel10k` directory?
Sorry for the confusion, that was indeed the issue (I wasn't using the latest version). This was due to a bug in a script I wrote for syncing my submodules...
> 
> Type `ls<tab>`. Does your prompt break?
> 
> Type `ZLE_RPROMPT_INDENT=1`. Does it help?
> 
> What's the output of `echo $ZSH_VERSION $ZSH_PATCHLEVEL`?

Thanks a lot!

**Comment by romkatv** [comment]
I'm glad it's working for you now.

By the way, if you really like to emulate Pure with Powerlevel10k, I have a config for it: https://gist.github.com/romkatv/7cbab80dcbc639003066bb68b9ae0bbf. Make sure to update Powerlevel10k to the latest version before using it.

**Comment by infokiller** [comment]
What's the difference between the config in that gist and the one in `.purepower` in your dotfiles?

**Comment by infokiller** [comment]
BTW I see some differences from real pure (left is real pure, right uses your gist):
image

**Comment by romkatv** [comment]
Pure Power doesn't attempt to emulate Pure. It uses a few tricks from Pure but overall it looks very different. No one can mistake Pure Power prompt for Pure.

`pure10k.zsh`, on the other hand, is an attempt to make prompt look as close as possible to Pure. It's almost indistinguishable. All differences are documented at the top of the file.

I don't mean to recommend `pure10k.zsh`. I find it quite awful myself.

**Comment by infokiller** [comment]
Gotcha, makes sense. I also prefer Pure Power, and this is from someone coming from the original Pure :)

**Comment by romkatv** [comment]
> BTW I see some differences from real pure (left is real pure, right uses your gist):

Again, this is really weird. It looks like you are using some other options that aren't defined in `pure10k.zsh`. Can you reproduce this issue from a clean zsh?

1. Type `zsh -df`.
2. Type this after fixing the paths:

```zsh
source /path/to/pure10k.zsh
source /path/to/powerlevel10k/powerlevel10k.zsh-theme
```

**Comment by romkatv** [comment]
Just a guess, did you type `source pure10k.zsh` into your prompt when it already had Powerlevel10k theme running? This is not supported. If you set or modify any of the `POWERLEVEL9K` parameters after the first prompt is rendered, things will break. See https://github.com/romkatv/powerlevel10k/#i-am-getting-an-error-zsh-bad-math-expression-operand-expected-at-end-of-string.

**Comment by infokiller** [comment]
> > BTW I see some differences from real pure (left is real pure, right uses your gist):
> 
> Again, this is really weird. It looks like you are using some other options that aren't defined in `pure10k.zsh`. Can you reproduce this issue from a clean zsh?
> 
> 1. Type `zsh -df`.
> 2. Type this after fixing the paths:
> 
> ```shell
> source /path/to/pure10k.zsh
> source /path/to/powerlevel10k/powerlevel10k.zsh-theme
> ```
Now it looks as expected!

**Comment by infokiller** [comment]
> Just a guess, did you type `source pure10k.zsh` into your prompt when it already had Powerlevel10k theme running? This is not supported. If you set or modify any of the `POWERLEVEL9K` parameters after the first prompt is rendered, things will break. See [romkatv/powerlevel10k#i-am-getting-an-error-zsh-bad-math-expression-operand-expected-at-end-of-string](https://github.com/romkatv/powerlevel10k/#i-am-getting-an-error-zsh-bad-math-expression-operand-expected-at-end-of-string).

I don't think so since I basically copied the content of that file to the local purepower file I used. I'll try to reproduce this with my zshrc and let you know if I can.

**Comment by romkatv** [comment]
> I don't think so since I basically copied the content of that file to the local purepower file I used.

That sounds good. Just make sure to _not_ type `source ~/.zshrc` afterwards. You need to either open a new shell session or type `exec zsh` to apply configuration changes without forking a process.

> I'll try to reproduce this with my zshrc and let you know if I can.

Thanks!

**Comment by infokiller** [comment]
> > > BTW I see some differences from real pure (left is real pure, right uses your gist):
> > 
> > 
> > Again, this is really weird. It looks like you are using some other options that aren't defined in `pure10k.zsh`. Can you reproduce this issue from a clean zsh?
> > 
> > 1. Type `zsh -df`.
> > 2. Type this after fixing the paths:
> > 
> > ```shell
> > source /path/to/pure10k.zsh
> > source /path/to/powerlevel10k/powerlevel10k.zsh-theme
> > ```
> 
> Now it looks as expected!

Ok so not exactly as expected: after clearing the screen (`C-L` in my case), there is still an empty line left at the top. I think this was an issue that used to be in pure as well. Screenshot (left is real pure):
image

**Comment by infokiller** [comment]
> > I don't think so since I basically copied the content of that file to the local purepower file I used.
> 
> That sounds good. Just make sure to _not_ type `source ~/.zshrc` afterwards. You need to either open a new shell session or type `exec zsh` to apply configuration changes without forking a process.
> 
> > I'll try to reproduce this with my zshrc and let you know if I can.
> 
> Thanks!

Just checked and it still works well with my zshrc. I think I may have had something badly configured in my zshrc when I saw the issue (I experimented with some changes).

**Comment by romkatv** [comment]
> Ok so not exactly as expected: after clearing the screen (C-L in my case), there is still an empty line left at the top. I think this was an issue that used to be in pure as well. Screenshot (left is real pure):

Oh, didn't know that. Thanks!

This is fixable (output the line from a `precmd` hook rather than via `PROMPT`) but I don't think it's worth it.

**Pull request closed without merging**
